### ISSUE TITLE
organic_results is missing the last result

### ISSUE THREAD

**Issue by lukeorland** [serpapi/google-search-results-python#13]
You get one fewer than the value you specify for `num` in the `organic_results` list

**Comment by hartator** [comment]
`num` parameter doesn't necessary match the number organic results we are getting back from Google. More information on how Google treat this kind of parameters: https://serpapi.com/pagination

(Sorry for the delay in the response. You can open bug reports on https://forum.serpapi.com, we'll check these boards on a daily basis.)
