### ISSUE TITLE
{'error':'We couldn't find your API Key.'}

### ISSUE THREAD

**Issue by rokintech** [serpapi/google-search-results-python#15]
`from serpapi.google_search_results import GoogleSearchResults

client = GoogleSearchResults({"q": "coffee", "serp_api_key": "************************"})

result = client.get_dict()`

I tried giving my API key from serpstack. Yet I am left with this error. Any help could be much useful.

**Comment by jvmvik** [comment]
Hi Rokintech,

Apologize for the delay.
Did you to contact the support from serpapi.com directly ?
This query is totally valid as long as the API key match the one available from http://serpapi.com/dashboard

**Comment by jvmvik** [comment]
I think you are mixing two different service.
This package is designed to work with serpapi.com
