### ISSUE TITLE
ImportError: cannot import name 'GoogleSearch' from 'serpapi'

### ISSUE THREAD

**Issue by mishra-avinash** [serpapi/google-search-results-python#16]
Hello,

I am trying to run the example on your git page https://github.com/serpapi/google-search-results-python#batch-asynchronous-searches
But constantly getting this error.

Thanks

**Comment by jvmvik** [comment]
Thanks for pointing this out. This example was out of date. I'd just fixed the documentation on the master branch.
Here is working version using Repl.it
https://repl.it/talk/share/Batch-asynchronous-search-using-SerpApicom/84676
