### ISSUE TITLE
KeyError when Calling Answer Box

### ISSUE THREAD

**Issue by ag-skyler** [serpapi/google-search-results-python#18]
I've attempted to get the results from the answer box using the [documentation here](https://serpapi.com/direct-answer-box-api).

I noticed the Playground does not return these results either. 

Is there any way to get this URL also?

### Output Returned when Attempting to Run the Sample Provided:

```
from serpapi import GoogleSearch

params = {
  "q": "What's the definition of transparent?",
  "hl": "en",
  "gl": "us",
  "api_key": ""
}

search = GoogleSearch(params)
results = search.get_dict()
answer_box = results['answer_box']
```

**Comment by ilyazub** [comment]
Hi @ag-skyler. This was fixed [some time ago](https://serpapi.canny.io/bugs/p/google-search-api-answerbox-not-scraping-properly).

![image](https://user-images.githubusercontent.com/282605/114682421-c0d62380-9d17-11eb-9c44-0d9dc96e5c78.png)

(Sorry for the delay in the response. You can open bug reports on https://forum.serpapi.com, we're checking these boards on a daily basis.)
