### ISSUE TITLE
Cannot increase the offset between returned results using pagination

### ISSUE THREAD

**Issue by samuelhaysom** [serpapi/google-search-results-python#24]
I am trying to use the pagination feature based on the code at (https://github.com/serpapi/google-search-results-python#pagination-using-iterator). I want to request 20 results per API call but pagination by default iterates by 10 results only instead of 20, meaning I my requests end up overlapping.

I think I have found a solution to this. Looking in the package, the pagination.py file has a Pagination class which takes a page_size variable that changes the size of the offset between returned results. 
The Pagination class is imported in the serp_api_client.py file within the pagination method starting on line 170 but here the page_size variable wasn't included. I just added page_size = 10 on lines 170 and 174 and now   I can use the page_size variable if I call search.pagination(page_size = 20). Can this change be made in the code?

**Comment by jvmvik** [comment]
fix by https://pypi.org/project/google-search-results/2.4.0/

**Comment by jvmvik** [comment]
however, I'm seeing duplicated result coming from Google time to time. 
You need to filter those in your Python code.
