### ISSUE TITLE
"error": "Missing query `q` parameter."

### ISSUE THREAD

**Issue by hshi420** [serpapi/google-search-results-python#33]
The url link gives me this message.

**Comment by dimitryzub** [comment]
Hi @hshi420, thank you for reaching out 🙂

1. Could you please provide a full traceback or a screenshot of the error?
2. Could you please provide a code snippet of your search `params`, or a screenshot? By search `params` I meant this:
```python
params = {
  "api_key": "...",
  "engine": "google",
  "q": "Coffee",
  "gl": "us",
  "hl": "en"
}
```
 
3. What API do you use? Google Search/Google Maps, etc?

I'll reopen this issue as we're not helped you yet 🙂

**Comment by dimitryzub** [comment]
@hshi420 Got it! That's great that the issue was solved 🙂 Thank you for clarifying, I'll close this issue then. Feel free to open if you need to.

**Comment by myrthebuckens** [comment]
I have the same issue! Even when I copy the code from the playground into my script I get this error.

I wrote the following: 

params = {
  "api_key": personal_key,
  "engine": "google_maps",
  "type": "search",
  "google_domain": "google.com",
  "q": "Coffee",
  "hl": "en",
  "ll": "@52.092876,5.104480,15.1z"
}

search = GoogleSearch(params)
results = search.get_dict()

**Comment by myrthebuckens** [comment]
The error is then the following:   "error": "Missing query `q` parameter."
}

**Comment by dimitryzub** [comment]
Hey, @myrthebuckens 🙂

A few obvious questions for the sake of clarity:

1. Did you `pip install` `google-search-results`?
2. Did you `import` it? Didn't see in your code snippet.
3. `personal_key` is a global variable? Have you tried passing [your SerpApi API key](https://serpapi.com/manage-api-key) directly to `"api_key"` under `params`? (`"api_key": "1111adsad131"`)

Looking forward to your reply ✨
