### ISSUE TITLE
How to get "related articles" links from google scholar via serpapi?

### ISSUE THREAD

**Issue by monk1337** [serpapi/google-search-results-python#34]
I am using SERP API to fetch google scholar papers, although there is always a link called "related articles' under each article but SERP API doesn't have any SERP URL to fetch data of those links?

<img width="633" alt="Screenshot 2022-07-14 at 3 05 07 AM" src="https://user-images.githubusercontent.com/17107749/178842094-33729d5f-4e6a-4a61-bf82-4cb57d33042b.png">

Serp API result : 

<img width="1142" alt="Screenshot 2022-07-14 at 3 15 16 AM" src="https://user-images.githubusercontent.com/17107749/178842205-4bf7195b-acd0-4566-9e4d-dff8e5c82f70.png">

Can I directly call this URL `https://scholar.google.com/scholar?q=related:gemrYG-1WnEJ:scholar.google.com/&scioq=Multi-label+text+classification+with+latent+word-wise+label+information&hl=en&as_sdt=0,21` using serp API?

**Comment by dimitryzub** [comment]
Hi, @monk1337 👋  

> Can I directly call this URL https://scholar.google.com/scholar?q=related:gemrYG-1WnEJ:scholar.google.com/&scioq=Multi-label+text+classification+with+latent+word-wise+label+information&hl=en&as_sdt=0,21 using serp API?

1. Yes you can. You just need to pass the `q=` URL value to SerpApi `q` search parameter. In the case of the URL provided by you, [SerpApi `q` parameter would be: `related:gemrYG-1WnEJ:scholar.google.com`](https://serpapi.com/playground?engine=google_scholar&q=related%3AgemrYG-1WnEJ%3Ascholar.google.com&hl=en):
![image](https://user-images.githubusercontent.com/78694043/178928026-e7fae011-6037-46e3-9ac2-7eac1d1dc6a8.png)

3. You can retrieve data directly from URL using only CURL and [JQ](https://stedolan.github.io/jq/). We have a `#AskSerpApi` episode that covers specifically this question: [#AskSerpApi: "How to extract a specific element from the JSON URL?" | CURL + JQ](https://www.youtube.com/watch?v=17odH_WIX4c).

To extract related articles, you need to access `["organic_results"]["inline_links"]["related_pages_link"]`:

![image](https://user-images.githubusercontent.com/78694043/178926863-1e184ed8-a293-4c14-900b-1bf6389bc90f.png)

Example code to extract related articles from the first page:

```python
from serpapi import GoogleSearch

params = {
  "api_key": "...",
  "engine": "google_scholar",
  "q": "Coffee",
  "hl": "en"
}

search = GoogleSearch(params)
results = search.get_dict()

for result in results["organic_results"]:
    related_articles = result["inline_links"]["related_pages_link"]
    print(related_articles)
```

Outputs (where `q=` is a related articles search query that can be passed to SerpApi `q` search parameter:

```lang-none
https://scholar.google.com/scholar?q=related:sWzmct-yYzgJ:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:9WouRiFbIK4J:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:fGeQlvu-2_IJ:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:-0fOFoq7wJ8J:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:CZSAb_VNDkkJ:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:Jt15QwxlEw0J:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:31GOrHWBl_AJ:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:KVT-hW9IrDoJ:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:Ang0MOfBmAUJ:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
https://scholar.google.com/scholar?q=related:QwF9cuvhnCoJ:scholar.google.com/&scioq=Coffee&hl=en&as_sdt=0,11
```

To access related articles with SerpApi, you can do it like so (keep in mind that this is an example):

```python
from serpapi import GoogleSearch
import re

def get_related_articles_query():
    params = {
      "api_key": "...",
      "engine": "google_scholar",
      "q": "Multi-label text classification",
      "hl": "en"
    }
    
    search = GoogleSearch(params)
    results = search.get_dict()

    related_articles = []

    for result in results["organic_results"]:
        # https://regex101.com/r/XuEhoh/1
        related_article = re.search(r"q=(.*)\/&scioq", result["inline_links"]["related_pages_link"]).group(1)
        related_articles.append(related_article)

    return related_articles


def get_related_articles_results():
    for related_article in get_related_articles_query():
        params = {
          "api_key": "...",
          "engine": "google_scholar",
          "q": related_article, # related:sWzmct-yYzgJ:scholar.google.com ...
          "hl": "en"
        }
        
        search = GoogleSearch(params)
        results = search.get_dict()

        for result in results["organic_results"]:
            print(result.get("title"), result.get("link"), result.get("publication_info", {}).get("summary"), sep="\n")

get_related_articles_results()
```

Outputs:

```lang-none
Deep learning for extreme multi-label text classification
https://dl.acm.org/doi/abs/10.1145/3077136.3080834
J Liu, WC Chang, Y Wu, Y Yang - … of the 40th international ACM SIGIR …, 2017 - dl.acm.org
...
```

Code example in the online IDE: https://replit.com/@DimitryZub1/Google-Scholar-SerpApi-API-Extract-Related-Articles

Let me know if it makes sense and if you need additional clarifications 🌼

**Comment by dimitryzub** [comment]
Closing this as we have implemented it. For more: https://serpapi.com/google-scholar-api
