### ISSUE TITLE
[Pagination] Pagination isn't correct and it skips index by one

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/google-search-results-python#38]
![image](https://user-images.githubusercontent.com/73674035/206139655-c7ae1d9c-e912-405a-a454-6693bfca1c2b.png)

Since the `start` value starts from `0`, the correct second page should be `10` and not `11`.

This behaviour is causing a skip in pages also. The customers are getting confusing results:
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/73674035/206140283-5db0b5b1-a208-48c6-89b0-55dd639a5e9d.png">

[Intercom Link](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/conversation/102910000035805)
First recognized by @marm123.

I think this part needs to be replaced by:
![image](https://downloads.intercomcdn.com/i/o/630528026/95ac20e1f0db551ee8973dfa/image.png)

```py
self.client.params_dict['start'] += 0
```

Whether it would cause any error on other engines is something I don't know. But it may also fix it for every other engine.

**Comment by dimitryzub** [comment]
A workaround of using `pagination()` with `parse_qsl`, `urlsplit` from `urllib.parse`:

```python
from serpapi import GoogleSearch
from urllib.parse import (parse_qsl, urlsplit)

params = {
    'api_key': '...',     # serpapi api key
    'engine': 'google',   # search engine
    'q': 'minecraft',     # search query
    'hl': 'en'            # language
    # 'start': 0          # or explicitly add page number
}

search = GoogleSearch(params)

# iterate over all pages
while True:
    results = search.get_dict()

    print(f"Currenlty on page: {params.get('start')}")

    if 'error' in results:
        print(results['error'])
        break

    # for result in results.get('organic_results', []):
    #     print(result.get('position'), result.get('title'), sep='\n')

    # check if the next page key is present in the JSON
    # if present -> split URL in parts and update to the next page
    if 'next' in results.get('serpapi_pagination', {}):
        search.params_dict.update(dict(parse_qsl(urlsplit(results.get('serpapi_pagination').get('next')).query)))
    else:
        break
```

Output:

```lang-none
Currenlty on page: None # first page. if 'start' param is present and set explicitly to 0, None will become 0
Currenlty on page: 10   # second page
Currenlty on page: 20
Currenlty on page: 30
Currenlty on page: 40
Currenlty on page: 50
Currenlty on page: 60
Currenlty on page: 70
```

Example from the <kbd>dashboard</kbd> -> <kbd>your searches</kbd> page ([Inspect last request](https://serpapi.com/searches/63db614a29d17789c27ab90b/inspect) (8th page), `next` hash key is empty thus exists pagination) :

![image](https://user-images.githubusercontent.com/78694043/216255933-3e28342f-3f18-478e-9ad7-37f01f62eb83.png)

![image](https://user-images.githubusercontent.com/78694043/216256079-53bc2dc8-9bcb-4499-929e-fa3efdf83fa6.png)
