### ISSUE TITLE
[Version] Update PyPi to include the most up-to-date version

### ISSUE THREAD

**Issue by marm123** [serpapi/google-search-results-python#39]
Currently, the PyPi allows users to install our library using pip easily. However, the library has been updated not to include the print method (screenshot below). The PyPi version still includes it, causing confusion among users. Some of them think that the printed URL should contain their data from search and contacting us about SerpApi not working, while others simply ask for this to be removed for clarity.

[Current state:
](https://github.com/serpapi/google-search-results-python/commit/d865add3a8286d7154ee1cf58eeefb5feb85dc63)<img width="698" alt="image" src="https://user-images.githubusercontent.com/28161162/224013758-46a01391-1c5e-43fe-9aac-78f7579b2547.png">

[The user confused about the data not being available in the printed link.
](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000037245?view=List)[Another user confused about the data not being available in the printed link
](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000037745?view=List)
[The user asking to remove the print method for clarity (they installed it through PyPi)
](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000038426?view=List)[Another user asking to remove the print method](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000035806?view=List)

[Link for account details for PyPi](https://app.slack.com/client/T9DETV55W/CMXP5GJAF)

**Comment by dimitryzub** [comment]
@marm123 we with @ilyazub has deployed a `2.4.2` which fixed this. Could you try on your end whenever you can?

**Comment by marm123** [comment]
@dimitryzub sure, I'll test it soon. Thanks!

**Comment by marm123** [comment]
Works great on my end! Thank you both, @dimitryzub and @ilyazub. I'm closing this thread.
