### ISSUE TITLE
..

### ISSUE THREAD

**Issue by jdfoxito** [serpapi/google-search-results-python#41]
...

**Comment by dimitryzub** [comment]
@jdfoxito thank you for opening this issue. 

What exact problem(s) were you facing? Based on your title:

1. "Free account doesn't work" - how exactly? No response when making a request? Have you passed [your SerpApi API key](https://serpapi.com/manage-api-key) to `api_key` under request `parameters`?

![image](https://user-images.githubusercontent.com/78694043/227859146-538187a3-52f6-404c-a13b-c0fb5cbbe488.png)

2. "Send code phone is failed". Could you provide a little bit more information so we can solve it? You haven't received an SMS with 6 digits?

Thank you.

**Comment by dimitryzub** [comment]
Closing it for now as no additional information has been received. Feel free to reopen 🙂
