### ISSUE TITLE
Connexion issue

### ISSUE THREAD

**Issue by redg25** [serpapi/google-search-results-python#5]
Hi,
One of the user using my code get the following error when creating a client.
![image](https://user-images.githubusercontent.com/52566911/60715036-68f07300-9f1c-11e9-81ca-3aec29fcdb3c.png)
I suppose it is machine settings related as it doesn't happen to other users.
Thanks for helping
P.S. I am fairly new to coding.

**Comment by hartator** [comment]
Hum maybe try to update your `OpenSSL` library on your computer? (It seems to have issue verifying to our SSL certificate.)
