### ISSUE TITLE
How to add proxy and ssl certs while using the Search API? I am currently trying to access it via my corporate network.

### ISSUE THREAD

**Issue by dee-walia20** [serpapi/google-search-results-python#52]
in the below code snippet, I can't find any option to add proxy settings or ssl certs like how you do with requests library.
```
from serpapi import GoogleSearch
search = GoogleSearch({
    "q": "coffee", 
    "location": "Austin,Texas",
    "api_key": "<your secret api key>"
  })
result = search.get_dict()
```

**Comment by hartator** [comment]
You don't need to add proxies and/or hack around SSL certifications. Everything is handled on https://serpapi.com/search end.
