### ISSUE TITLE
Knowledge Graph object not being sent in response.

### ISSUE THREAD

**Issue by lewismazzei** [serpapi/google-search-results-python#6]
Some queries which return a knowledge graph in both my own google search and when tested in the SerpApi Playground are not returning the 'knowledge_graph' key in my own application.

### Code:
```
params = {
    'q': 'Aspen Pumps Ltd',
    'engine': 'google',
    'api_key': <api_key>,
    'num': 100
  }

result_set = GoogleSearchResults(params).get_dict()

print(result_set.keys())
```

### Evaluation:
``` 
dict_keys(['search_metadata', 'search_parameters', 'search_information', 'ads', 'shopping_results', 'organic_results', 'related_searches', 'pagination', 'serpapi_pagination'])
```

### Manual Results:
https://www.google.com
<img width="1919" alt="Screenshot 2019-07-31 at 15 48 55" src="https://user-images.githubusercontent.com/17520107/62223112-526af980-b3ac-11e9-8974-dc2faedc8a79.png">

https://serpapi.com/playground
<img width="1919" alt="Screenshot 2019-07-31 at 15 49 10" src="https://user-images.githubusercontent.com/17520107/62223134-5a2a9e00-b3ac-11e9-81a3-2f7a23a62cc3.png">

**Comment by hartator** [comment]
@lewismazzei The knowledge graph might be not present in the search you've done with Python. Double check the HTML `raw_html_file` to see if that's the case or not.

A trick you can use to force the knowledge graph to show is to add "... company" at the end of your searches.
