### ISSUE TITLE
ImportError: cannot import name 'GoogleSearch' from 'serpapi'

### ISSUE THREAD

**Issue by nazib** [serpapi/google-search-results-python#63]
After creating a subscriber account in serpapi, I have been given an API key. I Installed the  "pip install google-search-results "

but whenever I tried to run my django app I get this error:

 File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/MyProjects/topsearch/topsearch/searchapp/models.py", line 3, in <module>
    from serpapi import GoogleSearch
ImportError: cannot import name 'GoogleSearch' from 'serpapi' (/Users/nazibabdullah/opt/miniconda3/envs/topsearch/lib/python3.8/site-packages/serpapi/__init__.py)

**Comment by medero** [comment]
Are you still getting it? Have you tried Python 3.7? At one point I think I got the same error but then I just re-did my requirements.txt and reinstalled it.. I also had to downgrade to Python 3.7 because was running into a segmentation fault with 3.8 and my specific docker instance - lemme know how it goes... curious

**Comment by nazib** [comment]
yep working now. Thanks so much

**Comment by medero** [comment]
Nice! For documentation-sake, what fixed it? Did you downgrade to Python 3.7, or?

**Comment by zeptoon** [comment]
Same issue, doesn't work out of the box (Python 3.9.0)

**Comment by ranfysvalle02** [comment]
I ran into the same issue, was able to work around it by:
```
import serpapi
```

and then doing serpapi.search(params_go_here) instead of GoogleSearch(params_go_here)

**Comment by 2282588541a** [comment]
same issue！！！

**Comment by m00t13** [comment]
The actual fix is to pip install google-search-results

**Comment by Shahidsaheb** [comment]
I also got the same issue.
Before, I just installed "pip install serpapi" and then tried to import "GoogleSearch", which gave me the same error.
Then I installed "pip install google-search-results" and tried again. It resolved the issue & I got the result.

**Comment by midniteclub** [comment]
> I ran into the same issue, was able to work around it by:
> 
> ```
> import serpapi
> ```
> 
> and then doing
> 
> ```
> serpapi.search(params_go_here) instead of GoogleSearch(params_go_here)
> ```

Tried to use SerpApi with GoogleSearch but still wasn't able to get things working with 'pip install google-search-results'. Setting 'results = serpapi.search(params)' and then converting the 'results' object to a pandas dataframe worked for me.

**Comment by KamiTzayig** [comment]
i there no other way around this?
im using python 3.12.4 and cant get this to work. would prefer not to do any hack and import it normally
error: 
`ImportError: cannot import name 'GoogleSearch' from 'serpapi' (unknown location)`

**Comment by ZiiS-ND** [comment]
I use this import
`from serpapi.google_search import GoogleSearch`

And it works normally.

**Comment by thisisvk45** [comment]
same issue！！！

**Comment by skoday** [comment]
If you are using python 3.12 chaces are it didn't install correctly, to fix just run:
pip uninstall google-search-results
pip uninstall serpapi
pip install google-search-results serpapi

that worked for me

**Comment by hilmanski** [comment]
Thanks for sharing your experience @skoday .

`serpapi` and `google-search-results` are two different libraries.

https://github.com/serpapi/google-search-results-python is our old library, but it still works fine as well. You only need to install one of them and uninstall the other one depending on which libraries you want to use.

For reference, here is the `serpapi` library repository: https://github.com/serpapi/SerpApi-python

**Comment by antoineego** [comment]
I just rebooted 👌 everything fine !

**Comment by marmiCcd** [comment]
@skoday Thank you so much, I searched for a solution for a couple of hours and even used chatgpt, but it turns out everything was so simple. I reinstalled serpapi several times using different methods and nothing helped, even changing the python version.

**Comment by hilmanski** [comment]
Hi, @marmiCcd , feel free to reach out to contact@serpapi.com, if you still encounter the issue.

**Comment by dnascimento** [comment]
Still happening

**Comment by schaferyan** [comment]
Hi @dnascimento - sorry to hear you encountered this issue.  For most users this is the result of a conflict between our two libraries.  As noted by my colleague in [one of the comments above](https://github.com/serpapi/google-search-results-python/issues/63#issuecomment-2849535564), you'll need to select which library you want to use and uninstall the other. If this doesn't resolve the problem for you, or you require any other assistance, please reach out to support at contact@serpapi.com, or via the chat interface on our website. We'll be more than happy to help.

**Comment by Zhuohao-Li** [comment]
still have `ImportError: cannot import name 'GoogleSearch' from 'serpapi'` when `from serpapi import GoogleSearch`. 
`Python 3.9.6`
`serpapi 0.1.5`
`google_search_results 2.4.2`
anything helps?

**Comment by schaferyan** [comment]
HI @Zhuohao-Li - sorry to hear you encountered this issue. The problem is most likely that you have the wrong library installed to run your code. It's a bit confusing as we have two Python libraries for SerpApi, and the two are not compatible.

Can you confirm if you ran:

```pip uninstall google-search-results
pip uninstall serpapi
pip install google-search-results serpapi

This works for most users who encounter this error. If you're still experiencing difficulties, please reach out to support via the chat interface on our website. Thanks for your patience!

**Comment by Zhuohao-Li** [comment]
> HI [@Zhuohao-Li](https://github.com/Zhuohao-Li) - sorry to hear you encountered this issue. The problem is most likely that you have the wrong library installed to run your code. It's a bit confusing as we have two Python libraries for SerpApi, and the two are not compatible.
> 
> Can you confirm if you ran:
> 
> ```
> pip uninstall serpapi
> pip install google-search-results serpapi
> ```
> 
> This works for most users who encounter this error. If you're still experiencing difficulties, please reach out to support via the chat interface on our website. Thanks for your patience!

Thanks, I think I have solve that just now :)

**Comment by ciertou** [comment]
> I ran into the same issue, was able to work around it by:
> 
> ```
> import serpapi
> ```
> 
> and then doing
> 
> ```
> serpapi.search(params_go_here) instead of GoogleSearch(params_go_here)
> ```

this is right answer to me.

**Comment by schaferyan** [comment]
> I ran into the same issue, was able to work around it by:
> 
> ```
> import serpapi
> ```
> 
> and then doing
> 
> ```
> serpapi.search(params_go_here) instead of GoogleSearch(params_go_here)
> ```

@ciertou and @midniteclub I'm glad to hear you were able to resolve this by using `serpapi.search(params_go_here) instead of GoogleSearch(params_go_here)`.

I want to note for clarity that this syntax is for our other (newer and still not officially supported) serpapi-pthon library, found at https://github.com/serpapi/serpapi-python

_This_ library, (google-search-results-python) does not support the `serpapi.search` syntax. If using _this_ library, the correct syntax is:

```
from serpapi import GoogleSearch
search = GoogleSearch({"q": "Coffee", "location": "Austin,Texas"})
search_result = search.get_dictionary()
```
Also note that this library is installed with `pip install google-search-results`, whereas `serpapi-python` (the newer lib) is installed with `pip install serpapi`.
