### ISSUE TITLE
get_html() Returns JSON Instead of HTML

### ISSUE THREAD

**Issue by schaferyan** [serpapi/google-search-results-python#66]
A customer reported the `get_html()` method for this library returns a JSON response instead of the expected HTML.

I may be misunderstanding something about what the `get_html` method is intended to do, but I checked this locally and the customer's report appears to be correct:

<img width="250" alt="Screenshot 2024-01-05 at 9 34 23 AM" src="https://github.com/serpapi/google-search-results-python/assets/30915304/8fe32506-cc6d-45e4-9b56-a24081b4c14a">

<img width="569" alt="Screenshot 2024-01-05 at 9 42 56 AM" src="https://github.com/serpapi/google-search-results-python/assets/30915304/2e2ed104-5fb8-4b39-b020-c352260d4d29">

**Comment by ilyazub** [comment]
Resolved in https://github.com/serpapi/google-search-results-python/pull/69. (Thanks @gutoarraes!)
