### ISSUE TITLE
Different results from serpapi (Google Trends) versus Google Trends site

### ISSUE THREAD

**Issue by robrady** [serpapi/google-search-results-python#68]
I'm having an issue (which is causing a serious headache / project issue for us) where the results from serpapi are different versus those returned from Google, when querying the website directly.

Below is a simple code snippet to reproduce:

```
from serpapi import GoogleSearch
import pandas as pd

PARAMS = {'engine': 'google_trends',
          'data_type' : 'RELATED_QUERIES',
          'q' : "health insurance",
          'geo': "IE",
          'date' : "2022-01-01 2022-12-31",
          'hl' : 'en-GB',
          'csv' : True,
          'api_key' : '[Key]'}

search = GoogleSearch(PARAMS) 
results = search.get_dict() 

rel = results['related_queries']['top']
df = pd.DataFrame(rel)

df[["query", "value"]]

df.to_csv("serpapi_results.csv")
```

Below is an image with the difference in results (and also attached are the files)
![image](https://github.com/serpapi/google-search-results-python/assets/4525496/5e59021d-300e-4a6e-b8be-1f26c47006c0)

This is an image of the URL in Google Trends:
![image](https://github.com/serpapi/google-search-results-python/assets/4525496/ac25a4e2-613a-4dd9-a774-08c5ca4166b2)

[serpapi_results.csv](https://github.com/serpapi/google-search-results-python/files/14587450/serpapi_results.csv)
[relatedQueries_google_results.csv](https://github.com/serpapi/google-search-results-python/files/14587453/relatedQueries_google_results.csv)

Can you let me know if this is a known issue or if I've made some mistake in my API call?
Thanks,
Ronan

**Comment by schaferyan** [comment]
Thank you @robrady, I'm closing this as it's documented in our Public Roadmap:

https://github.com/serpapi/public-roadmap/issues/1069
